apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardle-server
  namespace: wardle
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      securityContext:
        fsGroup: 65532
        runAsUser: 65532
      serviceAccountName: apiserver
      containers:
      - name: wardle-server
        image: quay.io/kubescape/storage-apiserver:debug
        volumeMounts:
          - mountPath: /data
            name: data
          - name: "cloud-config"
            mountPath: /etc/config
            readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: "cloud-config"
          configMap:
            name: "cloud-config"
            items:
            - key: "clusterData"
              path: "clusterData.json"
