apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardle-server
  namespace: wardle
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: wardle-server
        image: quay.io/kubescape/storage-apiserver:debug
        imagePullPolicy: Never
        volumeMounts:
          - name: "cloud-config"
            mountPath: /etc/config
            readOnly: true
      volumes:
        - name: "cloud-config"
          configMap:
            name: "cloud-config"
            items:
            - key: "clusterData"
              path: "clusterData.json"
